[build]
  # Directory that contains the deploy-ready HTML files and assets
  publish = "."

# Set caching, security, and CORS headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"

# Cache the CSV file to improve performance on subsequent visits
[[headers]]
  for = "/*.csv"
  [headers.values]
    Cache-Control = "public, max-age=86400" # Cache for 24 hours
    Access-Control-Allow-Origin = "*"
